// <auto-generated />
using System;
using Hollis.Toolbox.Functions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hollis.Toolbox.Functions.Migrations
{
    [DbContext(typeof(ToolboxDbContext))]
    [Migration("20251230173807_AddTablePastebinItem")]
    partial class AddTablePastebinItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Toolbox")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hollis.Toolbox.Functions.Entities.PastebinItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContentInDb")
                        .HasMaxLength(16384)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentStorageType")
                        .HasColumnType("int");

                    b.Property<bool>("Expired")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ExpiredAfter")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccessCode");

                    b.ToTable("PastebinItems", "Toolbox");
                });
#pragma warning restore 612, 618
        }
    }
}
